kind: pipeline
type: docker
name: test

workspace:
  base: /go
  path: src/github.com/deyung-shipt/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag

services:
  - name: db
    image: cockroachdb/cockroach:latest
    commands:
      - start-single-node --insecure
    
steps:
  - name: test
    image: golang:latest
    commands:
      - go test -coverprofile=coverage.txt ./...
  