kind: pipeline
type: kubernetes
name: test

workspace:
  base: /go
  path: src/github.com/deyung-shipt/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: test
    image: golang:latest
    commands:
      - apk add bash curl git make g++ gcc
      - go test -coverprofile=coverage.txt ./...
  