kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/github.com/deyung-shipt/${DRONE_REPO_NAME}

trigger:
  event:
    - push
    - pull_request
    - tag

services:
  - name: cockroachdb
    image: cockroachdb/cockroach:latest
    commands:
      - cockroach start-single-node --insecure
    
steps:
  - name: test
    image: golang:latest
    commands:
      - go test -coverprofile=coverage.txt ./...

  - name: build
    image: golang:latest
    environment:
      CGO_ENABLED: "0"
      GOOS: linux
      GOARCH: amd64
    commands:
      - go build -v -a -ldflags "-X main.version=build.${DRONE_BUILD_NUMBER}" -o build/docker/go-api-sample

  - name: docker
    image: plugins/docker
